# Generated by Django 2.1.7 on 2019-03-28 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usergroups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('github_url', models.URLField(blank=True, max_length=400)),
                ('linkedin_url', models.URLField(blank=True, max_length=400)),
                ('teamcreated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myteam', to='usergroups.Team')),
                ('teamenrolled', models.ManyToManyField(related_name='enrolledteam', to='usergroups.Team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
