# Generated by Django 2.1.7 on 2019-03-28 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='teamcreated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myteam', to='usergroups.Team'),
        ),
    ]
