# Generated by Django 2.1.7 on 2019-03-28 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190328_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='teamcreated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myteam', to='usergroups.Team'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='teamenrolled',
            field=models.ManyToManyField(blank=True, related_name='enrolledteam', to='usergroups.Team'),
        ),
    ]
