# Generated by Django 2.1.7 on 2019-03-28 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190328_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='github_url',
            new_name='github',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='linkedin_url',
            new_name='linkedin',
        ),
    ]
