# Generated by Django 2.1.7 on 2019-03-28 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190329_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='teamcreated',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='teamenrolled',
        ),
    ]
