# Generated by Django 2.1.7 on 2019-03-29 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usergroups', '0002_team_teamicon'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teamtask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True, default='', max_length=512)),
                ('status', models.CharField(choices=[('pl', 'Planned'), ('ip', 'In Progress'), ('do', 'Done'), ('st', 'Started')], default='pl', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ManyToManyField(related_name='assignedmem', to='usergroups.Team')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamtasks', to='usergroups.Team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='comment',
            name='task',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pl', 'Planned'), ('ip', 'In Progress'), ('do', 'Done'), ('st', 'Started')], default='pl', max_length=2),
        ),
        migrations.AddField(
            model_name='comment',
            name='teamtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskcomments', to='tasks.Teamtask'),
        ),
        migrations.AlterUniqueTogether(
            name='teamtask',
            unique_together={('title', 'team')},
        ),
    ]
