# Generated by Django 2.1.7 on 2019-03-30 20:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20190329_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.ManyToManyField(blank=True, related_name='assignee_mtem', to=settings.AUTH_USER_MODEL),
        ),
    ]
